namespace DRSSoftware.TextTemplateProcessor.Core;

/// <summary>
/// This is an enumeration of the different types of log entries that can be generated by the text
/// template processor. Each log entry type corresponds to a specific category of log messages,
/// allowing for better organization and filtering of log output.
/// </summary>
internal enum LogEntryType
{
    /// <summary>
    /// Identifies log messages pertaining to setup operations.
    /// </summary>
    Setup,

    /// <summary>
    /// Identifies log messages pertaining to reading and loading text template files.
    /// </summary>
    Loading,

    /// <summary>
    /// Identifies log messages pertaining to parsing of text template files.
    /// </summary>
    Parsing,

    /// <summary>
    /// Identifies log messages pertaining to the generation of the text output file.
    /// </summary>
    Generating,

    /// <summary>
    /// Identifies log messages pertaining to the writing of the text output file.
    /// </summary>
    Writing,

    /// <summary>
    /// Identifies log messages pertaining to reset operations.
    /// </summary>
    Reset,

    /// <summary>
    /// Identifies log messages pertaining to user interactions.
    /// </summary>
    User
}