global using System;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using DRSSoftware.TextTemplateProcessor.Core;
global using static DRSSoftware.TextTemplateProcessor.Core.GlobalConstants;
global using static DRSSoftware.TextTemplateProcessor.Core.Messages;
global using static DRSSoftware.TextTemplateProcessor.Core.RegexHelper;
global using static DRSSoftware.TextTemplateProcessor.TestShared.TestHelper;
global using FluentAssertions;
global using Moq;